# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 70daf59924e467c3253837dd79e1cf9879f0fb3b03d80419cb2ffb56a0fcdb7147eee4e9ca4625c5823da6036d87be7d036810647ba67efe9c02bcfb15f0acb4

test:
  secret_key_base: 95cd920326c7edfdf4a8ec8236fbb859dff4f92f03e778766e12ec749b8ffbe2e7d55945c4c8635a2537ce771dfbb05503034069188f3fa2692addfb1cb6bdc5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
